service: notification-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
  
functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - http:
          method: POST
          path: /sendMail
        
resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn