service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  
functions:
  hello:
    handler: src/handlers/sendMail.handler
    events:
      - http:
          method: GET
          path: /sendMail