service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}
  
functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - http:
          method: POST
          path: /sendMail